SECRET_KEY = 'secret_key'
SESSION_COOKIE_NAME='lc_session'
SUBJECT_ID_HASH_SALT = 'salt'
PREFERRED_URL_SCHEME = 'https'

DATA_FOLDER = "../data"

SCRIPT_LOCATION="lenticular_cloud:migrations"
SQLALCHEMY_DATABASE_URI = 'sqlite:///../data/db.sqlite'
SQLALCHEMY_TRACK_MODIFICATIONS = false


PKI_PATH = "../data/pki"
DOMAIN = 'example.com'
#SERVER_NAME = f'account.{ DOMAIN }:9090'

HYDRA_REQUEST_TIMEOUT_SECONDS = 3
HYDRA_ADMIN_URL = 'http://127.0.0.1:4445'
HYDRA_ADMIN_USER = 'lenticluar_cloud'
HYDRA_ADMIN_PASSWORD = 'notSecure'
HYDRA_PUBLIC_URL = 'http://127.0.0.1:4444'
SUBJECT_PREFIX = 'something random'

OAUTH_ID = 'identiy_provider'
OAUTH_SECRET = 'ThisIsNotSafe'


[LENTICULAR_CLOUD_SERVICES.jabber]
app_token = true
# client_cert= true


[LENTICULAR_CLOUD_SERVICES.mail-cardav]
app_token = true

# LENTICULAR_CLOUD_SERVICES = {
# 	'jabber': {
# 		'client_cert': True,
# 		'pki_config':{
# 			'email': '{username}@jabber.{domain}'
# 		},
#     'app_token': True
# 	},
# 	'mail-cardav': {
# 		'client_cert': False,
#     'app_token': True
# 	}
# }
